import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={roboto.className}>
          <Header />
          <main className="max-w-4xl mx-auto p-4">{children}</main>
        </body>
        <footer className="border-t p-8 text-center mt-16 text-gray-600">
          &copy; 2024 All rights reserved(Rampop)
        </footer>
      </html>
    </>
  );
}
